#!/bin/bash
wid=$1
class=$2
instance=$3
title=$(xdotool getwindowname $wid)

case $class in
	[Rr]edshift-*|[Gg]alculator|gnome-calculator|[Ff]eh|[Ss]xiv)
		echo "state = floating"
		echo "center = on"
		;;
	[Mm]pv)
		echo "sticky = on"
		echo "state = floating"
		;;
	mplab_ide)
		echo "desktop = ^3"
		;;
	discord)
		echo "desktop = ^5"
		;;
	spotify)
		echo "desktop = ^5"
esac

