#! /bin/bash
# ----------------- A E S T H E T I C S -------------------

# wal based script that does a bunch of stuff ($HOME/Scripts/wallpaper.sh)


# use a premade colorscheme with wal
# wallpaper="$HOME/Pictures/wallpapers/unixporn_discord/pape-master/moody_tumblr_vibes/pot.jpg"
wallpaper="$HOME/Pictures/wallpapers/lofi/spacerecordsnwt.png"

wal -n -q -a 90 --theme $HOME/.config/wal/colorschemes/dark/space_lofi.json

# source the colors. from pywal to use everywhere xresources gets used
. "${HOME}/.cache/wal/colors.sh"

FOREGROUND="$foreground"
BACKGROUND="$background"
BLACK="$color0"
RED="$color1"
GREEN="$color2"
YELLOW="$color3"
BLUE="$color4"
MAGENTA="$color5"
CYAN="$color6"
WHITE="$color7"


# automatically create a new solid color wallpaper from the background color

# convert -size 1920x1080 xc:"$background" $HOME/wallpaper.png


#generate gtk theme with oomox
oomox-cli -t ~/.themes --make-opts all -o pywal_theme  ~/.cache/wal/colors-oomox;

# things pywal should do automatically that dont work

# xwallpaper --zoom $HOME/wallpaper.png # restore wallpaper

xwallpaper --zoom $HOME/Pictures/wallpapers/lofi/spacerecordsnwt.png

betterlockscreen -u $HOME/Pictures/wallpapers/lofi/spacerecordsnwt.png

xrdb ~/.Xresources # reload XResources colors

# notifications daemon using pywal colors
killall dunst
dunst \
	-lb "$BACKGROUND" \
	-lf "$FOREGROUND" \
	-lfr "$GREEN" \
	-nb "$BACKGROUND" \
	-nf "$FOREGROUND" \
	-nfr "$BLUE" \
	-cb "$BACKGROUND" \
	-cf "$FOREGROUND" \
	-cfr "$RED" &

# compositor
killall picom
picom --config ~/.config/picom/picom.conf -b --experimental-backends --backend glx

# eye saver
# killall geoclue2
# exec /usr/lib/geoclue-2.0/demos/agent
killall redshift
killall redshift-gtk
# redshift -r -P -l geoclue2 -m randr -t 4000k:25000k &
redshift-gtk & # applet


# ------------------- status bar ---------------------------

# polybar

# killall polybar # status bar
# polybar bar &

# lemonbar
killall lemonbar
lemonbar-script &

killall stalonetray
killall nm-applet
nm-applet &
stalonetray -c ~/.config/.stalonetrayrc -bg "$background" &


# ---------------- important startups ----------------------

nm-applet & # network manager

xfce4-power-manager # power stuff for minimal wms
wmname compiz # fix java apps in minimal wms

killall sxhkd
sxhkd & # keyboard shortcuts

# If you want to use GNOME config tools...

#if test -x /usr/lib/openbox/gnome-settings-daemon >/dev/null; then
#  /usr/lib/openbox/gnome-settings-daemon &
#elif which gnome-settings-daemon >/dev/null 2>&1; then
#  gnome-settings-daemon &
#fi
#

# gnome keyring

# eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
# export SSH_AUTH_SOCK
